[tox]
envlist =
    py{312}-django{52}

[pytest]
DJANGO_SETTINGS_MODULE = ipware.tests.testsettings

[testenv]
deps =
    coveralls
    django52: Django>=5.2,<5.3
commands =
    coverage run --source=ipware manage.py test
    coverage report
    coverage xml
